### ISSUE TITLE
ошибка библиотеки

### ISSUE THREAD

**Issue by micruha** [DIYables/DIYables_4Digit7Segment_74HC595#1]
c:\Users\Lenovo\Arduino\libraries\DIYables_4Digit7Segment_74HC595\src\DIYables_4Digit7Segment_74HC595.cpp:34:1: error: 'static' may not be used when defining (as opposed to declaring) a static data member [-fpermissive]
   34 | static const byte DIYables_4Digit7Segment_74HC595::digitPatterns[16] = {
      | ^~~~~~

exit status 1

Compilation error: exit status 1

**Comment by DIYables** [comment]
Hello @micruha 

Which tool did you use to compile the code?
I compiled code with Arduino IDE 1.x and there is no error.

**Comment by micruha** [comment]
Hello.
I use Arduino IDE 2.1.0
![image](https://github.com/DIYables/DIYables_4Digit7Segment_74HC595/assets/120698813/84304b3f-d844-4f11-ad5a-f9a502080141)

**Comment by DIYables** [comment]
Dear @micruha 

I am sorry for the late reply. 
- I compiled the code for Arduino Uno on Arduino IDE 2.1.0 => no error
- I compiled the code for ESP32 on Arduino IDE 2.1.0 => error => I fixed and release new version 1.0.2.
It takes some our for Arduino Indexer to update the new version on the library manager.

**Comment by DIYables** [comment]
Problem solved
